# utils/exceptions.py
class ReiniciarProcessoException(Exception):
    """Exceção usada para indicar que o processo pode ser tentado novamente."""
    pass
